# This file was generated by GoReleaser. DO NOT EDIT.
class Bitbrew < Formula
  desc "bitbrew: BitBar plugin manager"
  homepage "https://github.com/micnncim/bitbrew"
  url "https://github.com/micnncim/bitbrew/releases/download/v0.1.1/bitbrew_0.1.1_darwin_amd64.tar.gz"
  version "0.1.1"
  sha256 "3d3f4b639d08bfde02232944e4b216aba867c138584e0293148f5e4083c22f38"

  def install
    bin.install "bitbrew"
  end

  test do
    system "#{bin}/bitbrew"
  end
end
