# This file was generated by GoReleaser. DO NOT EDIT.
class Chcase < Formula
  desc "chcase: CLI changing string cases"
  homepage "https://github.com/micnncim/chcase"
  url "https://github.com/micnncim/chcase/releases/download/v0.2.4/chcase_0.2.4_darwin_amd64.tar.gz"
  version "0.2.4"
  sha256 "3059226a29d0b6450f5695d3e5e0ac78ae90adb9398afd70bd668f77baf78ad0"

  def install
    bin.install "chcase"
  end

  test do
    system "#{bin}/chcase"
  end
end
