# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "GoReleaser playground"
  homepage "https://github.com/micnncim/goreleaser-playground"
  url "https://github.com/micnncim/goreleaser-playground/releases/download/v0.2.14/goreleaser-playground_0.2.14_darwin_amd64.tar.gz"
  version "0.2.14"
  sha256 "e96b41b8a5c1e045d7b85ff60fa358be0a59dbf56246611462ef62ba70f52931"

  def install
    bin.install "goreleaser-playground"
  end

  test do
    system "#{bin}/goreleaser-playground -v"
  end
end
