# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "GoReleaser playground"
  homepage "https://github.com/micnncim/goreleaser-playground"
  url "https://github.com/micnncim/goreleaser-playground/releases/download/v0.2.6/goreleaser-playground_0.2.6_darwin_amd64.tar.gz"
  version "0.2.6"
  sha256 "3f40c27c62d0f981151520730589a7f3bddd9c4cef2334d55ca96421d9b9c2a0"

  def install
    bin.install "goreleaser-playground"
  end

  test do
    system "#{bin}/goreleaser-playground -v"
  end
end
