# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "GoReleaser playground"
  homepage "https://github.com/micnncim/goreleaser-playground"
  url "https://github.com/micnncim/goreleaser-playground/releases/download/v0.2.8/goreleaser-playground_0.2.8_darwin_amd64.tar.gz"
  version "0.2.8"
  sha256 "5ee9123bc760df8f4e83a00d47da6471a5af67e168cd328576847ac1b7865701"

  def install
    bin.install "goreleaser-playground"
  end

  test do
    system "#{bin}/goreleaser-playground -v"
  end
end
