# This file was generated by GoReleaser. DO NOT EDIT.
class SelfupdatePlayground < Formula
  desc "selfupdate-playground"
  homepage "https://github.com/micnncim/selfupdate-playground"
  url "https://github.com/micnncim/selfupdate-playground/releases/download/v0.1.3/selfupdate-playground_0.1.3_darwin_amd64.tar.gz"
  version "0.1.3"
  sha256 "dfbd9391bfb88b1be193940ddc1504757ee7cdd8d00e0f2986e1083366ea5697"

  def install
    bin.install "selfupdate-playground"
  end

  test do
    system "#{bin}/selfupdate-playground"
  end
end
