# This file was generated by GoReleaser. DO NOT EDIT.
class SelfupdatePlayground < Formula
  desc "selfupdate-playground"
  homepage "https://github.com/micnncim/selfupdate-playground"
  url "https://github.com/micnncim/selfupdate-playground/releases/download/v0.1.4/selfupdate-playground_0.1.4_darwin_amd64.tar.gz"
  version "0.1.4"
  sha256 "28913bc5575a895758817ac497d2716847ae14038ea9de88116ff0d693a6a6e5"

  def install
    bin.install "selfupdate-playground"
  end

  test do
    system "#{bin}/selfupdate-playground"
  end
end
