# This file was generated by GoReleaser. DO NOT EDIT.
class Yreq < Formula
  desc "Sending multiple HTTP POST requests by JSON using YAML"
  homepage "https://github.com/micnncim/yreq"
  url "https://github.com/micnncim/yreq/releases/download/v0.1.1/yreq_0.1.1_darwin_amd64.tar.gz"
  version "0.1.1"
  sha256 "39e03fd3a8671fd51e090cd95b71412a0db97ce2c97c350f1ffba40183657aa1"

  def install
    bin.install "yreq"
  end

  test do
    system "#{bin}/goreleaser-playground -v"
  end
end
